### ISSUE TITLE
Module sterk verouderd

### ISSUE THREAD

**Issue by EvaP76** [ICEPAY/OpenCart-2.x#5]
De module werkt niet naar behoren en loopt 3 versies achter.
'Get payment methode' werkt niet. Haalt niets binnen.
Module is ook niet compatible met 2.2.0.0 zoals beweert op de site. 
Er is ook niets gewijzigd behalve de versie naam t.o.v. vorige module.

**Comment by tsygankov** [comment]
Hi EvaP76,

I have to use Google Translate, I hope I understood the problem correctly. 

We tested the compatibility of ICEPAY Payment Module [v2.0.8](https://github.com/ICEPAYdev/OpenCart-2.x/releases/tag/2.0.8) with OpenCart 2.2.0 and and haven't found any problems with "Get My Payment Methods" button. 

![opencart_22](https://cloud.githubusercontent.com/assets/15112699/22059791/fb57b696-dd76-11e6-8e90-09ea46d4c7cd.PNG)

Can you please check if Merchant ID and Secret Key settings are correct?

You can find more information about the module in [Manual for merchants and developers](https://icepay.com/downloads/pdf/manuals/opencart/Manual_2.0.8.pdf)

Please let me know if you have any questions.

**Comment by EvaP76** [comment]
Thank you for your reply.
But the current version is 2.3.0.2. It’s by far not compatible.
Also in the last version, only the version title has changed, but nothing in the code.
A new compatible version is long overdue.

Thanks.

**Comment by tsygankov** [comment]
Hi EvaP76,

At the moment we do not have a module that is compatible with OpenCart v2.3.x, however we started working on the problem yesterday.

As a workaround you can try using an ocmod extension that fixes v2.2-v2.3 compatibility issues, for example[ this one](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=27812). I can't guarantee that if will fix the compatibility issue because we haven't tested this solution yet.


> Also in the last version, only the version title has changed, but nothing in the code.

There are some minor changes between v.2.0.7 and v2.0.8 that fix the OpenCart 2.2.0 compatibility issues. 

You can review the changes by executing:

`git diff 2.0.7 2.0.8`

in .2.1.0b we introduced the [SendCloud ](https://www.sendcloud.nl/)integration.

You can review the changes by executing:

`git diff 2.0.8 2.1.0b`

Please let me know if you have any other questions.
